apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-client-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: catalogue-client
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: catalogue-client
    spec:
      containers:
      - name: catalogue-client
        image: lochlannoneill/catalogue-client:latest

