# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"W\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"!\n\x10RegisterResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"+\n\rLoginResponse\x12\x1a\n\x12\x61uthenticate_token\x18\x01 \x01(\t\"\"\n\x11GetDetailsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"H\n\x12GetDetailsResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t2\x9c\x01\n\x04User\x12\x31\n\x08Register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\"\x00\x12(\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\"\x00\x12\x37\n\nGetDetails\x12\x12.GetDetailsRequest\x1a\x13.GetDetailsResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST._serialized_start=14
  _REGISTERREQUEST._serialized_end=101
  _REGISTERRESPONSE._serialized_start=103
  _REGISTERRESPONSE._serialized_end=136
  _LOGINREQUEST._serialized_start=138
  _LOGINREQUEST._serialized_end=185
  _LOGINRESPONSE._serialized_start=187
  _LOGINRESPONSE._serialized_end=230
  _GETDETAILSREQUEST._serialized_start=232
  _GETDETAILSREQUEST._serialized_end=266
  _GETDETAILSRESPONSE._serialized_start=268
  _GETDETAILSRESPONSE._serialized_end=340
  _USER._serialized_start=343
  _USER._serialized_end=499
# @@protoc_insertion_point(module_scope)
