apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-client-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: user-client
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user-client
    spec:
      containers:
      - name: user-client
        image: lochlannoneill/user-client:latest

