apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-server-deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: catalogue-server
  minReadySeconds: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: catalogue-server
    spec:
      containers:
      - name: catalogue-server
        image: lochlannoneill/catalogue-server:latest
        ports:
        - containerPort: 50053

