# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import catalogue_pb2 as catalogue__pb2


class CatalogueStub(object):
    """Catalogue service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGames = channel.unary_unary(
                '/Catalogue/GetGames',
                request_serializer=catalogue__pb2.GetGamesRequest.SerializeToString,
                response_deserializer=catalogue__pb2.GetGamesResponse.FromString,
                )


class CatalogueServicer(object):
    """Catalogue service definition
    """

    def GetGames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGames,
                    request_deserializer=catalogue__pb2.GetGamesRequest.FromString,
                    response_serializer=catalogue__pb2.GetGamesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Catalogue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Catalogue(object):
    """Catalogue service definition
    """

    @staticmethod
    def GetGames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Catalogue/GetGames',
            catalogue__pb2.GetGamesRequest.SerializeToString,
            catalogue__pb2.GetGamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
