# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalogue.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61talogue.proto\"\x11\n\x0fGetGamesRequest\"!\n\x10GetGamesResponse\x12\r\n\x05games\x18\x01 \x03(\t2>\n\tCatalogue\x12\x31\n\x08GetGames\x12\x10.GetGamesRequest\x1a\x11.GetGamesResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalogue_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETGAMESREQUEST._serialized_start=19
  _GETGAMESREQUEST._serialized_end=36
  _GETGAMESRESPONSE._serialized_start=38
  _GETGAMESRESPONSE._serialized_end=71
  _CATALOGUE._serialized_start=73
  _CATALOGUE._serialized_end=135
# @@protoc_insertion_point(module_scope)
