apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: user-server
  minReadySeconds: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
      - name: greeter-server
        image: lochlannoneill/user-server:latest
        ports:
        - containerPort: 50051

