# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\"B\n\x0fPurchaseRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tgame_name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"3\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2;\n\x07Payment\x12\x30\n\x08Purchase\x12\x10.PurchaseRequest\x1a\x10.PaymentResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PURCHASEREQUEST._serialized_start=17
  _PURCHASEREQUEST._serialized_end=83
  _PAYMENTRESPONSE._serialized_start=85
  _PAYMENTRESPONSE._serialized_end=136
  _PAYMENT._serialized_start=138
  _PAYMENT._serialized_end=197
# @@protoc_insertion_point(module_scope)
